 #render.yaml

# Servicios de la aplicaci贸n
services:
  # Servicio web
  - name: web
    # Comando de construcci贸n
    buildCommand: npm install && npm run build
    # Comando de inicio
    startCommand: npm start
    # Configuraci贸n de CORS
    cors: cors.json

# Archivo de configuraci贸n CORS
files:
  - path: cors.json
    # Contenido del archivo
    content: |
      {
        "allow_origins": ["https://balponargprog.web.app"]
      }